config/routes.rb
Rails.application.routes.draw do

  root 'pages#landing'
  get 'pages/about'
  get 'pages/resume'
  get 'pages/contact'
  get 'pages/project1'
  get 'pages/project2'
  get 'pages/project3'
  get 'pages/project4'
  get 'pages/project5'
  get 'pages/project6'
  get 'pages/research'
  get 'pages/vision'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
 class PagesController < ApplicationController
  
  def landing
  end

  def about
  end

  def resume
  end

  def project1
  end

  def project2
  end
  
  def project3
  end
  
  def project4
  end

  def project5
  end

  def project6
  end

  def research
  end

  def vision
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/common/_spinner.html.erb
<div class="spinner">
  <div class="sk-fading-circle">
  <div class="sk-circle1 sk-circle"></div>
  <div class="sk-circle2 sk-circle"></div>
  <div class="sk-circle3 sk-circle"></div>
  <div class="sk-circle4 sk-circle"></div>
  <div class="sk-circle5 sk-circle"></div>
  <div class="sk-circle6 sk-circle"></div>
  <div class="sk-circle7 sk-circle"></div>
  <div class="sk-circle8 sk-circle"></div>
  <div class="sk-circle9 sk-circle"></div>
  <div class="sk-circle10 sk-circle"></div>
  <div class="sk-circle11 sk-circle"></div>
  <div class="sk-circle12 sk-circle"></div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VaibhavGupta</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/about.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
     </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-left">
       <li><%= link_to 'HOME', root_path %></li>
       <li><%= link_to 'ABOUT', pages_about_path %></li>
       <li><%= link_to 'CONTACT', pages_contact_path %></li>
       <li><%= link_to 'RESUME', pages_resume_path %></li>
      </ul> 
        
      <ul class="nav navbar-nav navbar-right">
        <a class="navbar-brand">VAIBHAV GUPTA</a>
      </ul>
    </div>
  </div>
</nav>
<body style="background-color:#bababa">
  <div class = "container">
    <div class="jumbotron" style="background-color:#fff;margin-top:10%">
        <h2 style="color:#969696;font-family: 'Lato-Regular', sans-serif">About Me</h2>
          <p style="color:#969696">I am a Multimedia Specialist and Video Game designer based of the former French colony of Pondicherry in India. I have lived in London for over two years, before returning to India in 2015 for a knee surgery following a motorcycle accident and to work on my own Video game start-up.<br /><br />
        I graduated in 2013 with a Bachelors in Computer Science and Engineering from Pondicherry University in India and in 2014 with a Masters in Video Game Development (Distinction) from Kingston University, London.<br /><br />
        My work at Kingston University during my masters involved my writing a paper on Narratology vs Ludology in Military simulators, in collaboration with Prof. Stephen J. Webley of Staffordshire University. I also worked with a team of students on Heroes of Meteropia, a game and a concept for the PSVITA which produced a tactile physical reward in the form of a Comic book of the user’s journey through the game. For my final project, I worked on the redesign and reboot of James Bond video games and my game 007 Elixir, which led to the completion of my degree with a distinction.<br /><br />
        </p>
        <h2 style="color:#969696;font-family: 'Lato-Regular', sans-serif">Work History</h2>
          <p style="color:#969696">I am the co-founder of Whiteraven Media Corp, a Digital media start up currently based of Bangalore in India. I am the lead video game designer at Whiteraven, where we are currently working on an untitled high end art and animation game based of the successful Ori and the Blind forest. <br /><br />
        My work prior to Whiteraven involved my working as an android application developer for Sunshine Concessions, based in Colorado, USA. I successfully studied their business practices and developed the Sunshine Point of sale system which is currently used by their business across the USA.<br /><br />
        On passing out from Kingston University in 2014, I worked as a Research and Teaching assistant at the university, where I assisted in teaching Theoretical Video Game studies, Digital Studio Practice, Business Analysis solutions and 3D modelling. I presented on occasion about Theoretical Game studies and design and Psychoanalysis of Video games.<br /><br />
        I have over two years of Video game development, UI and UX design experience across various organisations and projects.<br />
        </p>
        <h2 style="color:#969696;font-family: 'Lato-Regular', sans-serif">Other Work</h2>
          <p style="color:#969696">I am a recognised photographer and have worked in the past on Lonely Planet and National Geographic assignments in Baltistan, in the Himalayas.<br /><br />
        I am very passionate about designing video games and my pet project is a video game I am working on which is based on Fluid translation across glass surfaces. I have been working on this project with a psychology researcher from Cambridge and we are working on using this concept as a tool to stimulate parts of the human brain and in turn as an application to work on reducing the onset of Alzheimer’s disease.<br />
        </p> 
      </div>
  </div>
</body>

app/views/pages/contact.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
     </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-left">
       <li><%= link_to 'HOME', root_path %></li>
       <li><%= link_to 'ABOUT', pages_about_path %></li>
       <li><%= link_to 'CONTACT', pages_contact_path %></li>
       <li><%= link_to 'RESUME', pages_resume_path %></li>
      </ul> 
        
      <ul class="nav navbar-nav navbar-right">
        <a class="navbar-brand">VAIBHAV GUPTA</a>
      </ul>
    </div>
  </div>
</nav>
<body style="background-color:#bababa">
  <div class = "container">
    <div class="jumbotron" style="background-color:#fff;margin-top:10%">
        
        <h1 style="font-family:'Lato-Regular';color:#969696">CONTACT DETAILS:</h1>
  				
          <h3 style="font-family:'Lato-Regular';color:#969696">Phone: </h4>
            <p style="font-family:'Lato-Regular';font-size: 15px">00919047038948</p>
  			
        	<h3 style="font-family:'Lato-Regular';color:#969696">Email: </h4>
           <p style="font-family:'Lato-Regular';font-size: 17px">vaibhav2psp@hotmail.com</p>
  			
        	<h3 style="font-family:'Lato-Regular';color:#969696">Address: </h4>
          <p style="font-family:'Lato-Regular';font-size: 17px">338. Mahatma Gandhi Road, Pondicherry, India<br /><br />
  			
  	</div>
  </div>
</body>

     

app/views/pages/landing.html.erb
<div class="master-container" >
	<div class="container-fluid">
		<h2 class="name">VAIBHAV GUPTA</h2>
		<h4 class="designation">Designer. Leader. Visionary</h4>
		<div class="social-icons">
			<%= link_to image_tag('fb.png'), 'https://www.facebook.com/vaibhav2psp' %>
			<%= link_to image_tag('twitter.png'), 'https://twitter.com/vaibhav2psp' %>
			<%= link_to image_tag('linkedin.png'), 'https://uk.linkedin.com/in/vaibhav2psp' %>
			<%= link_to image_tag('instagram.png'), 'https://www.instagram.com/vaibhav2psp/' %>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-md-2 col-xs-12">
		<div class="header-group">
			<div class="header1"><%= link_to 'HOME', root_path %></div><br />
			<div class="header1"><%= link_to 'ABOUT',pages_about_path %></div><br />
			<div class="header1"><%= link_to 'CONTACT', pages_contact_path %></div><br />
			<div class="header1"><%= link_to 'RESUME', pages_resume_path %></div><br/>
		</div>
	</div>
<div class="col-md-10">
	<div class="container" style="overflow:hidden" >
		<div id = "profile" >
			<div class="col-md-6 col-xs-12">
				<%= link_to image_tag('007.png'), pages_project1_path, class: "project1" %>
				<span class="text"><span><%= link_to '007 ELIXIR GAMING PROJECT', pages_project1_path %></span></span>
			</div>
			<div class="col-md-6 col-xs-12">
				<%= link_to image_tag('domotz.jpg'), pages_project2_path, class: "project2" %>
				<span class="text"><span><%= link_to 'DOMOTZ UX PROJECT', pages_project2_path %></span></span>
			</div>
			<div class="col-md-6 col-xs-12" >
				<%= link_to image_tag('metropia4.jpg'), pages_project3_path, class: "project3" %>
				<span class="text"><span><%= link_to 'HEROES OF METEROPIA', pages_project3_path %></span></span>
			</div>
			<div class="col-md-6 col-xs-12" >
				<%= link_to image_tag('culture1.jpg'), pages_project4_path, class: "project4" %>
				<span class="text"><span><%= link_to 'CULTURE DABBA', pages_project4_path %></span></span>
			</div>
			<div class="col-md-6 col-xs-12" >
				<%= link_to image_tag('research1.jpg'), pages_project5_path, class: "project5" %>
				<span class="text"><span><%= link_to 'GAME RESEARCH', pages_project5_path %></span></span>
			</div>
			<div class="col-md-6 col-xs-12" >
				<%= link_to image_tag('future1.jpg'), pages_project6_path, class: "project6" %>
				<span class="text"><span><%= link_to 'FUTURE RESEARCH', pages_project6_path %></span></span>
			</div>
		</div>
	</div>
</div>
</div>

app/views/pages/project1.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
     </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-left">
       <li><%= link_to 'HOME', root_path %></li>
       <li><%= link_to 'ABOUT', pages_about_path %></li>
       <li><%= link_to 'CONTACT', pages_contact_path %></li>
       <li><%= link_to 'RESUME', pages_resume_path %></li>
      </ul> 
        
      <ul class="nav navbar-nav navbar-right">
        <a class="navbar-brand">VAIBHAV GUPTA</a>
      </ul>
    </div>
  </div>
</nav>
<div class="container-fluid">
  <h2 class="project-name">PROJECT NAME: 007 ELIXIR</h2>
  <div class="flexslider">
    <ul class="slides">
      <li class="project-image1"><%= image_tag('Elixir 1.png') %></li>
      <li class="project-image2"><%= image_tag('Elixir 2.png') %></li>
      <li class="project-image3"><%= image_tag('Elixir 3.png') %></li>
      <li class="project-image4"><%= image_tag('Elixir 4.png') %></li>
      <li class="project-image5"><%= image_tag('Elixir 5.png') %></li>
      <li class="project-image6"><%= image_tag('Elixir 6.png') %></li>
    </ul>
  </div>
  <h3 style="text-align:center">Objective</h3>

  <p style="margin-left:20%;margin-right:20%">The project was taken up with the aim to redesign and reintroduce the James Bond game franchise back into the modern world. The James Bond Video games from the 90s were the most successful and sought after videogames of the period.</p><br />

  <h3 style="text-align:center">My Role</h3>

  <p style="margin-left:20%;margin-right:20%">My work aimed at reintroducing the franchise, produced the conception and design of 007 elixir, a sandbox game with extremely realistic graphics and mechanics based on the Rockstar Advanced Game Engine (RAGE).</p><br />

  <h3 style="text-align:center">Outcome</h3>

  <p style="margin-left:20%;margin-right:20%">A new parallel mission line plot mechanic was created to increase replay value and leave room for future sequels.With this game, a new reactive narrative has been created known as the ‘Hybrid Narrative’, which continually responds and reacts to the player’s successes and failures across the course of the game, leading to greatly enhanced replay value of the game.We have also introduced a new memoirs mode. The memoirs mode is based on an old and retired Bond reminiscing over the various missions he participated in, in his younger days. This gives us endless room for future sequels. It also blends in perfectly with our HYBRID narrative, where actions of the player alter the story greatly.
  </p><br />

  <p style="margin-left:20%;margin-right:20%">A detailed analysis of this project can be found <%= link_to 'here', 'http://vaibhav2psp.wixsite.com/myportfolio/elixir' %></p>

    <h3 class="prev"><%= link_to 'Prev Project','#' %></h3>
    <h3 class="next"><%= link_to 'Next Project', pages_project2_path %></h3>
  </div>

app/views/pages/project2.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
     </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-left">
       <li><%= link_to 'HOME', root_path %></li>
       <li><%= link_to 'ABOUT', pages_about_path %></li>
       <li><%= link_to 'CONTACT', pages_contact_path %></li>
       <li><%= link_to 'RESUME', pages_resume_path %></li>
      </ul> 
        
      <ul class="nav navbar-nav navbar-right">
        <a class="navbar-brand">VAIBHAV GUPTA</a>
      </ul>
    </div>
  </div>
</nav>
<div class="container-fluid">
  <h2 class="project-name">PROJECT NAME: DOMOTZ</h2>
  <div class="flexslider">
    <ul class="slides">
      <li class="project-image1"><%= image_tag('domotz.jpg') %></li>
      <li class="project-image2"><%= image_tag('domotz2.jpg') %></li>
      <li class="project-image3">><%= image_tag('domotz3.JPG') %></li>
      <li class="project-image4"><%= image_tag('domotz4.png') %></li>
    </ul>
  </div>
  <h3 style="text-align:center">Objective</h3>

  <p style="margin-left:20%;margin-right:20%">In 2014, I was approached by the Anglo Italian home automation company Domotz to come up with designs for their home automation mobile application. The challenge here was to complete the design in 20 hours.</p><br />

  <h3 style="text-align:center">My Role</h3>

  <p style="margin-left:20%;margin-right:20%">The idea is to represent the master panel for 50 devices present in a house. The master panel should allow access to complete details of each device and controls to them. This must be achieved in one page on a tablet device, a page which can be scrollable/swipeable.</p><br />

  <h3 style="text-align:center">Outcome</h3>

  <p style="margin-left:20%;margin-right:20%">The layout and system produced displays all the 50 devices in one page (scroll up or down) and provides basic direct usable details readily on the initial screen. When extended detail is required, the device is selected and the screen expands to display the detailed information i.e. the 50x”12”s 12 extra parameter section. Once the necessary tasks are performed and the view is then collapsed and the user can move to another device by scrolling up or down.I came up with three different designs, each transitioning to the next, leading to a final design which formed the basis of domotz’s current mobile User Interface and Experience.

  </p><br />

  <p style="margin-left:20%;margin-right:20%">A detailed analysis of this project can be found <%= link_to 'here', 'http://vaibhav2psp.wixsite.com/myportfolio/domotz' %></p>

    <h3 class="prev"><%= link_to 'Prev Project', pages_project1_path %></h3>
    <h3 class="next"><%= link_to 'Next Project', pages_project3_path %></h3>
  </div>

app/views/pages/project3.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
     </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-left">
       <li><%= link_to 'HOME', root_path %></li>
       <li><%= link_to 'ABOUT', pages_about_path %></li>
       <li><%= link_to 'CONTACT', pages_contact_path %></li>
       <li><%= link_to 'RESUME', pages_resume_path %></li>
      </ul> 
        
      <ul class="nav navbar-nav navbar-right">
        <a class="navbar-brand">VAIBHAV GUPTA</a>
      </ul>
    </div>
  </div>
</nav>
<div class="container-fluid">
  <h2 class="project-name">PROJECT NAME: HEROES OF METEROPIA</h2>
  <div class="flexslider">
    <ul class="slides">
      <li class="project-image1"><%= image_tag('metropia4.jpg') %></li>
      <li class="project-image2"><%= image_tag('metropia.jpg') %></li>
      <li class="project-image3"><%= image_tag('metropia2.jpg') %></li>
      <li class="project-image4"><%= image_tag('metropia3.jpg') %></li>
    </ul>
  </div>
  <h3 style="text-align:center">Objective</h3>

  <p style="margin-left:20%;margin-right:20%">Whilst at Kingston University, my team and I were asked to design a game for Sony PlayStation, worthy of redeeming the failure console, the PSVITA, generating a novel concept to generate positive revenue. The game to be designed had to also utilize the PSVITA, key hardware features such as the front and rear touch inputs, the dual analog sticks and the ability of its OpenGL OS to process augmented reality using its rear facing camera.</p><br />

  <h3 style="text-align:center">My Role</h3>

  <p style="margin-left:20%;margin-right:20%">I worked as the Lead Game Designer and Project manager in a team of six comprising of two Digital Artists, two UX and UI Designers and one Programmer. My role was to come up with the main game concept, run the weekly scrum sessions and handle the creative production of the project.
  </p><br />

  <h3 style="text-align:center">Outcome</h3>

  <p style="margin-left:20%;margin-right:20%">TWe produced Homemade Heroes, a game which takes the player through a mystery thriller tale, with the ability to generate his/her own Homemade Hero and fight crime along the way.What set the game apart was the concept of tactile rewards, where the player could during his gameplay customize his/her progress in comic format and at the end of the day, produce his/her own comic book with his/her own customized adventure, which Sony could then print and deliver at a price.With endless combinations and adventures, both single and multiplayer, the game fulfilled the brief given to us by both Sony and Kingston University.
  </p><br />

  <p style="margin-left:20%;margin-right:20%">A detailed analysis of this project can be found <%= link_to 'here', 'http://vaibhav2psp.wixsite.com/myportfolio/heroes-of-meteropia' %></p>

    <h3 class="prev"><%= link_to 'Prev Project', pages_project2_path %></h3>
    <h3 class="next"><%= link_to 'Next Project', pages_project4_path %></h3>
  </div>

app/views/pages/project4.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
     </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-left">
      <li><%= link_to 'HOME', root_path %></li>
       <li><%= link_to 'ABOUT', pages_about_path %></li>
       <li><%= link_to 'CONTACT', pages_contact_path %></li>
       <li><%= link_to 'RESUME', pages_resume_path %></li>
      </ul> 
        
      <ul class="nav navbar-nav navbar-right">
        <a class="navbar-brand">VAIBHAV GUPTA</a>
      </ul>
    </div>
  </div>
</nav>
<div class="container-fluid">
  <h2 class="project-name">PROJECT NAME: CULTURE DABBA</h2>
  <div class="flexslider">
    <ul class="slides">
      <li class="project-image1"><%= image_tag('CD1.png') %></li>
      <li class="project-image1"><%= image_tag('CD3.png') %></li>
      <li class="project-image1"><%= image_tag('CD4.png') %></li>
      <li class="project-image1"><%= image_tag('CD5.png') %></li>
      <li class="project-image1"><%= image_tag('CD6.png') %></li>
      <li class="project-image1"><%= image_tag('CD2.png') %></li>
    </ul>
  </div>
  <h3 style="text-align:center">Objective</h3>

  <p style="margin-left:20%;margin-right:20%">I currently work as a Digital Product Manager at a Minneapolis based startup called CultureDabba. CultureDabba is a subscription service which promotes Indian culture to American kids of Indian origin in the age band of 5-9 years.</p><br />

  <h3 style="text-align:center">My Role</h3>

  <p style="margin-left:20%;margin-right:20%">I handle all the digital initiatives of CultureDabba and explore new avenues to produce captivating content. I create their monthly comic strips, animated cartoons and videos and write and edit articles for the magazine. I manage a team of three extremely talented artists who work to contribute digital artwork for the magazine. I am also working on producing augmented reality games and maintaining the CultureDabba mobile app.</p><br />

  <h3 style="text-align:center">Outcome</h3>

  <p style="margin-left:20%;margin-right:20%">The CultureDabba subscriber base has grown considerably since my joining the team in June 2016. We started with a subscriber base of 50 and have now quadrupled the amount in three months and the response to our social media presence had grown in the thousands! We’ve grown from physical activities and content to active digital content and are continuing to grow extensively!</p><br />

    <h3 class="prev"><%= link_to 'Prev Project',pages_project3_path %></h3>
    <h3 class="next"><%= link_to 'Next Project', pages_project5_path %></h3>
  </div>

app/views/pages/project5.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
     </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-left">
       <li><%= link_to 'HOME', root_path %></li>
       <li><%= link_to 'ABOUT', pages_about_path %></li>
       <li><%= link_to 'CONTACT', pages_contact_path %></li>
       <li><%= link_to 'RESUME', pages_resume_path %></li>
      </ul> 
        
      <ul class="nav navbar-nav navbar-right">
        <a class="navbar-brand">VAIBHAV GUPTA</a>
      </ul>
    </div>
  </div>
</nav>
<div class="container-fluid">
  <h2 class="project-name">PROJECT NAME: GAME RESEARCH</h2>
  <div class="flexslider">
    <ul class="slides">
      <li class="project-image1"><%= image_tag('game1.jpg') %></li>
      <li class="project-image2"><%= image_tag('game2.jpg') %></li>
      <li class="project-image3"><%= image_tag('game3.jpg') %></li>
      <li class="project-image4"><%= image_tag('game4.jpg') %></li>
      <li class="project-image5"><%= image_tag('game5.png') %></li>
      <li class="project-image6"><%= image_tag('game6.jpg') %></li>
    </ul>
  </div>
  <h3 style="text-align:center">A BRIEF SUMMARY OF MY RESEARCH</h3>

  <p style="margin-left:20%;margin-right:20%">My work at Kingston University during my masters involved my writing a paper on Narratology vs Ludology in Military simulators, I did psychological research work on various video game design aspects including realism in video games and simulators. This submission on Military simulation won me attention and laurels from various recognised scholars in the UK. This research was done in collaboration with Prof. Stephen J. Webley of Staffordshire University. This piece of work established my indepth understanding of game creation. I have always been passionate about making games more real and true to life and my current research work focusses on ‘Defining realism in games’, which as every Video game academic knows is a Grey area and my work with Dr. Webley has helped us identify that Social Realism is a true form of realism in Video games. My next work goes into authoring a paper titled ‘Defining Social realism in games and understanding its relationship with player immersion’. I believe that the above research would help us design I believe that this would help us better understand on how to work on producing more realism in video games with acceptance from the audience. This would also help us understand more techniques in achieving greater immersion of the audience in video games.
</p><br />

    <h3 class="prev"><%= link_to 'Prev Project',pages_project4_path %></h3>
    <h3 class="next"><%= link_to 'Next Project', pages_project6_path %></h3>
  </div>